version: '3.9'
services:
  tg_bot:
    image: python:3.11-slim
    container_name: minify_link_bot
    command: ["python3", "main.py"]
    environment:
      - TG_API_KEY=${TG_API_KEY}
    volumes:
      - ./:/app
      - ./.env:/app/.env:ro
    working_dir: /app
    restart: always
    ports:
      - "8080:80"
      - "8443:443"
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "3"
